config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  namespace :admin do
    resources :receipes
  end

end

app/views/layouts/admin/_column-left.html.erb
<div class="col-lg-8">
  
  <!-- /.column-charts -->
  
  <!-- /.column-timeline -->
</div>

app/views/layouts/admin/_messages.html.slim
- message = flash
- if !message[:error].blank?
  .alert.alert-danger
    = flash[:error]
- if !message[:success].blank?
  .alert.alert-success.alert-dismissable
    button.close type="button" data-dismiss="alert" aria-hidden="true" ×
    = flash[:success]

app/views/layouts/admin/_navbar_static_side.html.slim
.navbar-default.sidebar role="navigation"
  .sidebar-nav.navbar-collapse
    ul.nav#side-menu
      li.sidebar-search
        .input-group.custom-search-form
          input.form-control type="text" placeholder="Search..."
          span.input-group-btn
            button.btn.btn-default type="button"
              i.fa.fa-search
      li
        a href="#"
          = t("admin.receipes.title")
          span.fa.arrow
        ul.nav.nav-second-level
          li
            = link_to t("admin.receipes.menu.new"), new_admin_receipe_path
          li
            = link_to t("admin.receipes.menu.index"), admin_receipes_path

app/views/layouts/admin/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <%= render partial: 'layouts/admin/navbar_header' %>

  <!-- /.navbar_top_links -->


  <%= render partial: 'layouts/admin/navbar_static_side' %>
</nav>

app/views/layouts/admin/_row_page_title.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= yield :page_title %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>