config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  namespace :admin do
    resources :receipes
  end

end

app/models/receipe.rb
# == Schema Information
#
# Table name: receipes
#
#  id            :integer          not null, primary key
#  name          :string
#  level         :integer
#  time_to_do    :integer
#  obs           :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  category_id   :integer
#  url           :string
#  author        :string
#  category_name :string
#  cover         :string
#


class Receipe < ActiveRecord::Base
  COLUMNS = [
    :id,
    :name,
    :category_name,
    :steps_count,
    :ingredients_count
  ]

  attr_accessor :score
  has_many :ingredient_instructions, dependent: :destroy
  has_many :ingredients, through: :ingredient_instructions

  has_many :steps, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :ingredient_instructions, :reject_if => :all_blank, :allow_destroy => true

  before_save :set_counters
  after_save :set_recommendation

  mount_uploader :cover, ReceipeCoverUploader

  MENU_GROUPS = [
    I18n.t("receipe.menu_group.breakfest"),
    I18n.t("receipe.menu_group.lunch_dinner")
  ]

  acts_as_taggable_on :cuisines, :occasions, :allergies, :diets

  def self.similarities_for(id)
    recommender = ReceipeRecommender.new
    similarities = []
    recommends = recommender.similarities_for(id, with_scores: true)
    return [] if recommends.blank?
    recommends.each do |recommend|
      score = recommend[1].round(3)
      receipe_id = recommend[0]
      receipe = Receipe.find(receipe_id)
      receipe.score = score
      similarities << receipe
    end
    similarities
  end

  def similars
    Receipe.similarities_for(self.id)
  end

  def main_ingredients
    self.ingredient_instructions.
    where(weight: IngredientInstruction::WEIGHTS["Primary"]).
    map(&:ingredient)
  end

  def secundary_ingredients
    self.ingredient_instructions.
    where(weight: IngredientInstruction::WEIGHTS["Secondary"]).
    map(&:ingredient)
  end

  def common_ingredients
    self.ingredient_instructions.
    where("weight = '?' OR weight IS NULL", IngredientInstruction::WEIGHTS["Common"]).
    map(&:ingredient)
  end

  def set_counters
    self.steps_count = self.steps.count
    self.ingredients_count = self.ingredient_instructions.count
  end


  def columns
    COLUMNS
  end

  def set_recommendation
    recommender = ReceipeRecommender.new
    self.main_ingredients.each do |main_ingredient|
      recommender.add_to_matrix(:main_ingredients, main_ingredient.name, self.id.to_s)
    end

    self.secundary_ingredients.each do |secundary_ingredient|
      recommender.add_to_matrix(:secundary_ingredients, secundary_ingredient.name, self.id.to_s)
    end

    self.common_ingredients.each do |comun_ingredient|
      recommender.add_to_matrix(:common_ingredients, comun_ingredient.name, self.id.to_s)
    end

    self.cuisine_list.each do |cuisine|
      recommender.add_to_matrix(:cuisines, cuisine, self.id.to_s)
    end

    self.occasion_list.each do |occasion|
      recommender.add_to_matrix(:occasions, occasion, self.id.to_s)
    end

    recommender.add_to_matrix(:categories, self.category_name.parameterize, self.id.to_s)

    recommender.process_items!(self.id.to_s)

    # recommender.add_to_matrix!(:ingredients, "frango", "frango xadres", "frango agridoce", "strogonoff", "frango a milanesa", "frango ao creme de leite")
    # recommender.add_to_matrix!(:ingredients, "creme de leite", "frango ao creme de leite", "strogonoff", "macarrao de frango ao molho branco")
    # recommender.add_to_matrix!(:users, "yuri", "strogonoff")
    # recommender.similarities_for("strogonoff")
  end
end

app/controllers/admin/receipes_controller.rb
class Admin::ReceipesController < ApplicationController
  respond_to :html, :json

  def index 
    @receipes = Receipe.order(order).page(current_page).per(per_page)
    respond_to do |format|
      format.html
      format.json { render json: to_json } 
    end
  end


  def to_json
    total_count = @receipes.total_count
    {
      # draw: 1, 
      recordsTotal: total_count, recordsFiltered: total_count, 
      data: attributes
    }
  end

  def columns
    Receipe::COLUMNS
  end

  def attributes
    @receipes.map do |object|
      attrs = object.columns.map {|p| object.send(p)} 
      Hash[object.columns.zip(attrs)]
    end
  end
  
  def new
    @receipe = Receipe.new
  end
  
  def create
    @receipe = Receipe.new(receipe_params)
    if @receipe.save
      flash[:success] = I18n.t("admin.receipes.messages.create_success")
      redirect_to admin_receipes_path
    else
      flash[:error] = I18n.t("admin.receipes.messages.error")
      render action: :new
    end
  end

  def edit
    @receipe = Receipe.find(params[:id])
  end

  def update
    @receipe = Receipe.find(params[:id])
    if @receipe.update_attributes(receipe_params)
      flash[:success] = I18n.t("admin.receipes.messages.update_success")
      redirect_to admin_receipes_path
    else
      flash[:error] = I18n.t("admin.receipes.messages.error")
      render action: :edit
    end 
  end

  def show
    @receipe = Receipe.find(params[:id])
  end

  private
  def receipe_params
    params.require(:receipe).permit(
        :name, :author, :category_name, :url, :cover, :menu_group, :time_to_do, :yield,
        :cuisine_list, :occasion_list, :allergy_list, :diet_list,
        steps_attributes: [:id, :_destroy, :description, :scope, :position],
        ingredient_instructions_attributes: [:id, :_destroy, :name, :how, :quantity, :metering, :scope, :weight]
    )
  end

  def current_page
    if params["start"]
      (params["start"].to_i - params["length"].to_i) + 2
    else
      params["page"] || 1
    end
  end

  def per_page
    params["length"] || 10
  end

  def order
    if params["order"]
      ordering = params["order"]["0"]
      col = ordering["column"].to_i
      {columns[col] => ordering["dir"]}
    else
      {"created_at" => "desc"}
    end
  end
end

app/views/admin/receipes/_form.html.slim
- 2.times { @receipe.steps.build } if @receipe.steps.empty?
- 2.times { @receipe.ingredient_instructions.build } if @receipe.ingredient_instructions.empty?
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading= yield :receipe_heading
      .panel-body
        .row
          .col-lg-12
            = simple_form_for(@receipe, url: url, html: { class: 'form-vertical', role: 'form', multipart: true }) do |f|
              .row
                .col-lg-6
                  = f.input :name
                .col-lg-6
                  = f.input :category_name
              .row
                .col-lg-3
                  = f.input :menu_group, collection: Receipe::MENU_GROUPS
                .col-lg-3
                  = f.input :yield
                .col-lg-3
                  = f.input :time_to_do
              .row
                .col-lg-6
                  = f.input :author
                .col-lg-6
                  = f.input :url
              .row
                .col-lg-12
                  .panel.panel-default
                    .panel-heading Tags
                    .panel-body
                      .row
                        .col-lg-6
                          = f.input :cuisine_list, input_html: {value: @receipe.cuisine_list.try(:to_s)}
                        .col-lg-6
                          = f.input :occasion_list, input_html: {value: @receipe.occasion_list.try(:to_s)}
                        .col-lg-6
                          = f.input :allergy_list, input_html: {value: @receipe.allergy_list.try(:to_s)}
                        .col-lg-6
                          = f.input :diet_list, input_html: {value: @receipe.diet_list.try(:to_s)}    
              .row
                .col-lg-6
                  = f.input :cover, as: :file

              .row
                .col-lg-6
                  .row
                    .col-lg-12
                      .panel.panel-default
                        .panel-heading= t('.ingredients-heading')
                        .panel-body
                          .row
                            .col-lg-12                
                              #ingredient_instructions
                                = f.simple_fields_for :ingredient_instructions do |ingredient_instruction|
                                  = render 'ingredient_instruction_fields', :f => ingredient_instruction
                                .links
                                  = link_to_add_association t('admin.receipes.add_ingredient'), f, :ingredient_instructions
                .col-lg-6
                  .row
                    .col-lg-12
                      .panel.panel-default
                        .panel-heading= t('.steps-heading')
                        .panel-body
                          .row
                            .col-lg-12
                              #steps
                                = f.simple_fields_for :steps do |step|
                                  = render 'step_fields', :f => step

                                .links
                                  = link_to_add_association t('admin.receipes.add_step'), f, :steps
              = f.submit t("admin.receipes.save"), class: 'btn btn-primary'

app/views/admin/receipes/_ingredient_instruction_fields.html.slim
.nested-fields
  .row
    .col-lg-6
      = f.input :name
    .col-lg-6
      = f.input :scope
  .row
    .col-lg-3
      = f.input :quantity
    .col-lg-3
      = f.input :metering
    .col-lg-6
      = f.input :how
  .row
    .col-lg-6
      = f.input :weight, as: :select, collection: IngredientInstruction::WEIGHTS.map {|k, v| [k, v]}, include_blank: false
  = link_to_remove_association t('admin.receipes.remove_ingredient'), f

app/views/admin/receipes/_step_fields.html.slim
.nested-fields
  .row
    .col-lg-12
      = f.input :description
  .row
    .col-lg-6
      = f.input :position
    .col-lg-6
      = f.input :scope
  / = f.input :position
  = link_to_remove_association t('admin.receipes.remove_step'), f

app/views/admin/receipes/edit.html.slim
- content_for :page_title, t('admin.receipes.title')
- content_for :receipe_heading, t('.heading')
= render 'form', url: admin_receipe_path(@receipe)

app/views/admin/receipes/index.html.slim
- content_for :page_title, t('admin.receipes.title')
.table-responsive
  table.table.table-striped.m-b-none#dt
    thead
      tr
        - @receipes.first.columns.each do |column|
          th= column
    tbody
      / - @receipes.each do |receipe|
      /   tr
      /     td= receipe.name
      /     td= receipe.category_name
      /     td= receipe.steps_count
      /     td= receipe.ingredients_count
      tr
        td[colspan="4"]
          | Loading...
- content_for :js_bottom do
  javascript:
    ls = new ListDataTable('receipes', ['id', 'name', 'category_name', 'steps_count', 'ingredients_count']); ls.load()

/ .row
/   .col-lg-2
/     .panel-heading Receipe Table
/     .panel-body
/       .dataTable_wrapper
/         .dataTables_wrapper.form-inline.dt-bootstrap.no-footer#dataTables-example_wrapper
/           .row
/             .col-sm-6
/               #dataTables-example_length
/                 label 
/                   select.form-control.input-sm aria-controls="dataTables-example" name="dataTables-example_length"
/                     option value="10" 10
/                     option value="25" 25
/                     option value="50" 50
/                     option value="100" 100
/                   / entries
/             .col-sm-6
/               .dataTables_filter#dataTables-example_filter
/                 label 
/                   input.form-control.input-sm aria-controls="dataTables-example" placeholder="" type="search"
/           .row
/             .col-sm-12
/               table.table.table-striped.table-bordered.table-hover.dataTable.no-footer#dataTables-example aria-describedby="dataTables-example_info" role="grid"
/                 thead
/                   tr role="row"
/                     th aria-label="Name: activate to sort column descending" aria-sort="ascending" style="width: 154px;" colspan="1" rowspan="1" aria-controls="dataTables-example" tabindex="0" class="sorting_asc" Name
/                 tbody
/                   - @receipes.each do |receipe|
/                     tr.gradeA.odd role="row"
/                       td.sorting_1= receipe.name
          / .row
          /   .col-sm-6

    / - 
    /   p= receipe.name

app/views/admin/receipes/new.html.slim
- content_for :page_title, t('admin.receipes.title')
- content_for :receipe_heading, t('.heading')
= render 'form', url: admin_receipes_path(@receipe)

app/views/admin/receipes/show.html.slim
.bg-light.lter.b-b.wrapper-md

  .pull-right.header-buttons

    = link_to "Listar todas as receitas", admin_receipes_path, class: "btn btn-success first-button"
    = link_to "Editar receita", edit_admin_receipe_path(@receipe), class: "btn btn-info"

h1= @receipe.name
h3 Steps
ul
  - @receipe.steps.each do |step|
    li= "#{step.position} #{step.description}" 
h3 Ingredients
ul
  - @receipe.ingredient_instructions.each do |ingredient_instruction|
    li= ingredient_instruction.full_instruction
= image_tag @receipe.cover.url

h3 Similar Receipes
.table-responsive
  table.table.table-striped.m-b-none#dt
    thead
      tr
        th Id
        th Nome
        th Proximidade
    tbody
      - @receipe.similars.each do |similar_receipe|
        tr
          td
            = link_to "visualize #{similar_receipe.id}", admin_receipe_path(similar_receipe), class: 'label bg-primary'
          td= similar_receipe.name
          td= similar_receipe.score